name: Test common

on:
  pull_request:
    branches: [main]
    paths:
      - 'common/**'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  test-common:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run common checks for common component
        uses: ostis-ai/test-conan@0.1.0
        with:
          directory: 'common'
