name: Test common

on:
  pull_request:
    branches: [main]
    paths:
      - 'common/**'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  test-common:
    runs-on: ubuntu-latest
    
    steps:
      - name: Run common checks for common component
        uses: ./common-checks/
        with:
          directory: 'common'
